Add kafka waiting resource
betalo-sweden/await pull request #41
Opened 2020-09-14 08:21 UTC by fcristovao

Hello,

  I would like to introduce the capability of waiting on `kafka` resources.
  Use case: when setting up kafka clusters, it's good to know when they are ready to serve requests.
  Additionally, I've seen cases where systems expect certain topics to exist on connection time, so I've added the capacity to wait for certain topics to be configured.

  I've selected https://github.com/segmentio/kafka-go as the library for kafka, but could've really been something else. This one just seemed ok for the job. It does however, require `go 1.12+`, so please let me know if that is unacceptable.

  I've added the respective testing for Kafka, but I've marked the tests as skipped if they don't find a kafka instance available to run the tests. I have used a docker compose setup locally to do the testing, but wasn't sure if you'd like me to commit that in the repo as well. Please let me know and I can add it as well.

2020-09-14 08:31 UTC, fcristovao commented on awaiter.go
> +						return
I'm not particularly happy with this approach, although "it works".

The point of this is to allow the resources to report errors in the fragment section (e.g., `...#sasl=wrong`).
It's not an availability error (as it's not recoverable, as the resource doesn't know what the user intended).
This will eventually exit with an error on `main.go`

However, it will only fail whenever the resource in question is _reached_ (imagine waiting on 4 resources, and only when reaching the last, we exit saying that you misconfigured `await` itself).

I would rather have an approach that would have each resource "validate" itself on construction. This would ensure that errors in configuration would be caught immediately.

2020-09-15 16:41 UTC, fcristovao commented on awaiter.go
> +						return
I went for another approach, that kept this file the same, and solved the issues I was referring to.

2020-09-16 07:49 UTC, fcristovao commented
@AshrafAnsari Hey again!
I don't know if you get notified for new PRs, so pinging you directly 🙈

2020-09-16 07:56 UTC, AshrafAnsari commented
@fcristovao Hi! Sorry if things are taking too long. Unfortunately, I'm a bit swamped at the moment. I'll have a look at this asap. I'll see if someone else can help with the review in the meantime. But thanks a lot for your submissions. I think this might come in handy for us as well pretty soon, as we've also been talking about Kafka lately.

2020-09-16 07:59 UTC, fcristovao commented
No worries at all!
I just didn't know if this was showing up anywhere (I'm used to having automatic assignees/reviewers showing in the PRs).
And thank you once again!

2020-09-18 06:31 UTC, kyeett requested changes
* Check if tests can fail
* Supply docker compose to test TLS and SASL
* Prefer to use uuid.New().String() instead of newString()

2020-09-18 06:31 UTC, kyeett commented on kafka_test.go
> +		Topic:             newString(20), // Ensure that a random name is used
replace with uuid.New().String() from https://github.com/google/uuid

2020-09-18 06:31 UTC, kyeett commented on kafka_test.go
> +func newString(length int) string {
Can be removed if uuid.New().String() is used

2020-09-18 06:31 UTC, kyeett commented on kafka_test.go
> +}
When I try to run the tests locally the plaintext ones **always** succeed. Whether I have kafka running or not. Could you double check that this isn't the case on your side?

Also, could you supply a docker-compose that has also supports the 9093 TLS and 9094 SASL, that would be great.

2020-09-18 09:14 UTC, fcristovao commented on kafka_test.go
> +		Topic:             newString(20), // Ensure that a random name is used
I can do that, but I don't agree that is a better approach.
All the code requires is a randomString, not a UUID, even if in string form (so the semantics are not the same), and I also don't think that avoiding 10 lines of code in a test are worth bringing in another dependency.

I will at least rename it to `randomString(20)` though.

That being said, if you really want me to, I will make the change to `uuid.New().String()`.

2020-09-18 09:14 UTC, fcristovao commented on kafka_test.go
> +func newString(length int) string {
Check other comment.

2020-09-18 09:17 UTC, fcristovao commented on kafka_test.go
> +}
I'll add the docker-compose. I had it on my machine, so I'll just commit those :)

I'll double check the always succeeding, and add more negative tests (I notice now that those are missing)

2020-09-22 11:32 UTC, HaraldNordgren commented
We are running 1.12.x on some our services still, and I know that there was a problem updating at least one of them recently (ABC).

So until that is resolved, I'm not sure we can drop Go 1.12 support, unfortunately.

2020-09-22 20:18 UTC, fcristovao commented
@HaraldNordgren I'll check what I can do regarding Go 1.12. Theoretically, `kafka-go` was supposed to be 1.12+ according to their [own docs](https://github.com/segmentio/kafka-go#golang-version), but maybe they're outdated.

I'm working on the other elements that have been raised.
The thing that I wasn't expecting is actually that `kafka-go` seems to hang whenever it connects to, for example, a http server, instead of throwing an error. Once I've fixed that problem, I'll update the PR.

2020-09-23 10:08 UTC, fcristovao commented
@HaraldNordgren I've managed to make it compatible with go `1.12.x` again, by downgrading the `kafka-go` version.
Since we use so little of it, it should be more than ok.

I had to force push because I realised that my commits were being done with the wrong e-mail. I've now fixed that.

Please let me know if anything else is necessary :)

2020-09-24 06:45 UTC, kyeett commented on kafka_test.go
> +		Topic:             newString(20), // Ensure that a random name is used
Yes, I would prefer to use `uuid.New().String()`. If you want to make it clear, you can hide it behind a function `randomTopicString()`, or similar.  

This is a test dependency, so I don't think introducing it is a problem. If we are worried about adding dependencies, I would worry more about introducing `kafka-go` into the binary itself :-)

2020-09-24 06:55 UTC, fcristovao commented on kafka_test.go
> +		Topic:             newString(20), // Ensure that a random name is used
Fixed

2020-10-05 07:23 UTC, fcristovao commented
Could I get a review again? :)

2020-10-23 07:32 UTC, fcristovao commented
@AshrafAnsari Hello again :)
I wondered if I could get reviews again?

2020-11-17 12:59 UTC, fcristovao commented
Hey again, 
This PR has been opened for over 2 months now, and I no longer know what to do.
Am I to consider that await is abandoned by Betalo?

2021-01-11 13:44 UTC, fcristovao commented
Hello.
Any updates on this?

2021-01-15 10:47 UTC, AshrafAnsari commented
@fcristovao Hi! Very sorry that we've been taking forever to reply. But sadly however, you are right. This is no longer maintained due to changed priorities. I'm sorry to have to tell you this. So unfortunately, the only option right now is to fork this.

2021-01-15 13:42 UTC, fcristovao commented
@AshrafAnsari Thank you! It's completely ok that you no longer support it :)
I'll fork it then :)
And happy new year!

2021-02-10 13:14 UTC, closed without merging